version: '3.5'

services:

  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./api:/api:rw
  #     - /api/node_modules
  #   ports:
  #     ['8080:8080']
  #   environment:
  #     WAIT_HOSTS: db:3306

  db:
    container_name: portfolio_db
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock
    ports:
      ['3306:3306']

  # app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./app:/app:rw
  #     - /app/node_modules
  #   restart: always
  #   ports:
  #     ['80:3000']